.MODEL SMALL
.STACK 100H
.DATA
    MSG DB 'Hello, WORLD!$', 0
.CODE

MAIN PROC
    MOV AX, @DATA
    MOV DS, AX   
    
    MOV AH, 09H
    LEA DX, MSG ;lOAD eFFECTIVE ADDRESS OF MSG
    INT 21H
    MAIN ENDP
END MAIN